### ISSUE TITLE
How to search local image (without url) using Google lens by python.

### ISSUE THREAD

**Issue by xin-ran-w** [serpapi/google-search-results-python#73]
I have a image store in my local device, and I want to search it on web, here is my code, but it didn't work.

```python
    def encode_pil_to_base64(image):
        buffered = BytesIO()
        image.save(buffered, format="JPEG")
        img_str = base64.b64encode(buffered.getvalue()).decode()
        return img_str
    
    image_url = f"data:image/jpeg;base64,{encode_pil_to_base64(image)}"

    params = {
        "engine": "google_lens",
        "url": image_url,
        "api_key": os.getenv("SERP_API_KEY"),
        "hl": "en",
        "country": "US"
    }
    search = GoogleSearch(params)
    results = search.get_dict()
```
The error is shown here:
```
Traceback (most recent call last):
  File "tools.py", line 272, in ...
    results = search.get_dict()
  File "/envs/hddesp/lib/python3.10/site-packages/serpapi/serp_api_client.py", line 103, in get_dict
    return self.get_dictionary()
  File ".../anaconda3/envs/hddesp/lib/python3.10/site-packages/serpapi/serp_api_client.py", line 96, in get_dictionary
    return dict(self.get_json())
  File ".../anaconda3/envs/hddesp/lib/python3.10/site-packages/serpapi/serp_api_client.py", line 83, in get_json
    return json.loads(self.get_results())
  ....
  File ".../anaconda3/envs/hddesp/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

**Comment by hilmanski** [comment]
Hi @xin-ran-w,

We apologize for the delayed response. For a faster response, we suggest reaching out to contact@serpapi.com. You're correct; we currently do not support using an image from a local file. Our engineers are currently working on this feature request: https://github.com/serpapi/public-roadmap/issues/948

In the meantime, you can upload the local image to any public image hosting and use the link later on. Here is the related tutorial: https://serpapi.com/blog/building-an-image-based-search-app-with-google-lens-api/

I hope it helps. I'll close this thread for now as it's not directly related to the SDK.
